### PR TITLE
Feature/cg 495 persistentVolume, persistentVolumeClaim, storageClass

### PR DESCRIPTION
**Pull request by tyler-dunkel**

### CODE REVIEW

**Review by csbrandt — COMMENTED** [review]
doest seem to be related to this pr but I am seeing that all `k8sMetadata` objects coming back with a null id
Screen Shot 2022-01-05 at 1 49 10 PM

**Comment by csbrandt** [comment]
these json payloads are useless from a graphql perspective, you should be able to parse the payload, e.g. `formatIamJsonPolicy` in the AWS provider (recursively in this case)
Screen Shot 2022-01-05 at 1 54 10 PM

**Comment by tyler-dunkel** [comment]
> doest seem to be related to this pr but I am seeing that all `k8sMetadata` objects coming back with a null id Screen Shot 2022-01-05 at 1 49 10 PM

This is on purpose because in some cases metadata is nested under a template object which has an id. However, I can just repeat the `uid` that I am pulling up so it is always there.

**Comment by tyler-dunkel** [comment]
> these json payloads are useless from a graphql perspective, you should be able to parse the payload, e.g. `formatIamJsonPolicy` in the AWS provider (recursively in this case) Screen Shot 2022-01-05 at 1 54 10 PM

I am not sure this can be done as these json objects can contain anything in the config object and annotations can also be simple `{key: value}` as well. I will add a ticket to investigate further later.

**Review by csbrandt — APPROVED** [review]

**Pull request merged**
